//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using WPFRelectionControls;

namespace DbController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Whore()
        {
            this.Orders = new HashSet<Order>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int Id { get; set; }
        [DynamicExtractable]
        public string FirstName { get; set; }
        [DynamicExtractable]
        public string LastName { get; set; }
        [DynamicExtractable]
        public Nullable<int> Age { get; set; }
        public Nullable<int> PimpId { get; set; }
        [DynamicExtractable]
        public Nullable<decimal> PricePerHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [DynamicExtractable]
        public virtual Pimp Pimp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
