//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;

namespace DbController
{
    using System;
    using System.Collections.Generic;
    
    public partial class Whore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Whore()
        {
            this.Orders = new HashSet<Order>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int Id { get; set; }
        [DynamicExtractable]
        public string FirstName { get; set; }
        [DynamicExtractable]
        public string LastName { get; set; }
        [DynamicExtractable]
        public Nullable<int> Age { get; set; }
        public Nullable<int> PimpId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Pimp Pimp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
